[google_service_account]
type = "service_account"
project_id = "dashboardenom"
private_key_id = "bc1b4dd01061bc10d90fc78f2d6871be0817143b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPUWKKBJCptzYT
f3JPTe/OaRR8mXwF/yG82ghtvMEvm7PQWQ2GMM0o/UJKbwbM9wBa7NAltRV/0DAZ
Q5P24iF7SCAIhrRDDUfjyrtqDg5dqdC3VqLlUiWm635kYIUNY3fJ9vRDq2sU4jm0
BBsDyCKV7SF499Nm7EOrgNTU+ju6Wx3snEQjYAF2Wxdg6JJi6wHriJUZQFeGQKeO
cj1/zufRvYOInBLwVk+WheKooKaKxJn90vSFCZgda8SLbJNgzz2beFQftVQIzjmO
ufnuc1eRWzecteTEXecRy2lngD5iyvQ8Kk2mpAZO/AWsZwz5Sn+pBAkMAj8Q9uls
/1L15ciBAgMBAAECggEAAiCbKsBmPZ+YKfYOVbr+gXc5kxe+Go+mKHpySLH9p3/p
BfPL/DsG9+s1YW8nOjY0pjo03pYvnMqlm7TCUW+7mTjBv2Smd+Osf61mY+21/wcN
kbwNWt4PbdmPx/bnlp4VLhjfI8ygAixaHDtIja7hj/lJdSTR4gX9ocZmKLNSppRh
CgJSOHoMAnm8THXNUSMI4QncUEDMZPXoL9SQrAj64Nx/CmlD3rAJVVLB3G8RchOE
J9+uxlR2rb/BoFbgu0rkcKPnDFIT5rB+8Jo2cMFKruxfl6iVeSkXDldqgcDPkpQY
tB755aD0jrRk+BeC6Ws9qcb0WxRW2phQu6v6Mvef6wKBgQD4JpbmCHMGNnsQhlR4
c7G/8AleOPhOfC+iNZztLmnphZ0k05a0Fa6d++bseinrZ1Ad/CeL0ihBovABF9ae
ecN+TegmbpLGwCU3LFfVd4Y7hQYoNomoY87/dFH0xMRcKbuWQmqC/zRM1rgQDNyG
vak+TRrY1PPD932TuV9nQkjaWwKBgQDV4CZl/F7OgykCyESgVX1kNvr8+JoDa8ij
O/8vu4sX3NQVRfCEXjY/E3Lsl44wI6jtrZpppUaXrqjrk167jATOhHCC4Hr5GhFD
cPsntmjZutj0vXghEPlo4N0O7r8vinV4KLGCejFqChSAAG3ITjl94OjyiKLG4LCY
5QgVNzOHUwKBgQDgl3SNn+oTHm4Fh76eAgBHeoXQDHnX9xfZlPKBzDc5jp+qfAJy
3Qjcnefj8bFNCIV/jf9w0fVzangUVTH+3q+r+fD6D6uyTKeiJvUcFACekAgBj1LJ
4AOyOuIOSaR60Z6hIV1rUHVScifHBwz0umWaKIj65Mn3fGDgua76Mwji7wKBgDlA
Gic8qggvtd+nyi79E2arDP6AcYGu7XM8kS+uzSnjE+Zp5VsZeP3jb+UDIK2kLgkJ
aocTFdVujIsa1MXxUiwR6agu/NwHbU2XRbO4sVJvILpKqYh4abr4TlQ79nN8Zbt3
cSTTHr0a26fz9W8j+WHHvbOGfcQsyzjyPfqn3yQ/AoGAWaXJn607QU4Qwu4n1ikL
TFuEb2bLz7gH84YrcSpmNEjx7lQKp1xr/LLtaBIRa6je9uOctTsribhXEtHhUCi1
xA25oxJ4XFXdszqV33npXereO3YUdCfkR6TZgIlOdaE9UtW8qnZHPfGsHFORFEJs
JsXyuM4poIAbGjClkzer9Ao=
-----END PRIVATE KEY-----
"""
client_email = "dashboardenom@dashboardenom.iam.gserviceaccount.com"
client_id = "101425631575143348756"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dashboardenom%40dashboardenom.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[google_oauth]
client_id = "720091660714-fbk6m3q7di42ah0lcgc6an20r6jha0tp.apps.googleusercontent.com"
project_id = "dashboardenom"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
redirect_uris = ["http://localhost"]
